server:
  port: 8444
  ssl:
    enabled: true
    bundle: "server-b-ssl"

spring:
  application:
    name: server-b
  cloud:
    vault:
      host: localhost
      port: 8200
      scheme: http
      authentication: TOKEN
      token: demo-root-token
      kv:
        enabled: true
        backend: secret
        default-context: ssl-certs

  ssl:
    bundle:
      pem:
        server-b-ssl:
          reload-on-update: false
          keystore:
            certificate: "vault:secret/data/ssl-certs/server-b"
          truststore:
            certificate: "vault:secret/data/ssl-certs/server-b"

logging:
  level:
    com.demo: DEBUG
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG
    io.github.gridadev: DEBUG